name = "fastapi"
compatibility_date = "2024-04-02"

[vars]
UPSTASH_REDIS_REST_TOKEN = "Ab-QASQgYzQzOTczMDEtMTI3ZC00NDFiLWI0OTItMGM4YjBhNjJiMzUzMmY1MDZhMDE1YjZkNDllZjhmNTQ3YmEyMWI1NjQxYTE="
UPSTASH_REDIS_REST_URL = "https://daring-octopus-49040.upstash.io"